[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=🩳 虚拟机,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/IPDiverter.list
ruleset=🅱🆃,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/bt.list
ruleset=🏴‍☠️ 追加规则,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/add.list
ruleset=⚓ GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=⚓ GitHub,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/github.list
ruleset=🚀 手动切换-1,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/%F0%9F%9A%80%20%E6%89%8B%E5%8A%A8%E5%88%87%E6%8D%A2-1.list
ruleset=🇨🇳 追加规则,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/add-cn.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 🇨🇳 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ZhihuAds/ZhihuAds.list
ruleset=🛑 🇨🇳 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AdvertisingMiTV/AdvertisingMiTV.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=💬 Ai,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/ai.list
ruleset=☁ 🅲🅵,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/Cloudflare-SUFFIX.list
ruleset=☁ 🅲🅵,https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/Cloudflare-IP.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=🚀 手动切换-1`select`.*
custom_proxy_group=🩳 虚拟机`select`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]DIRECT
custom_proxy_group=🅱🆃`select`[]DIRECT`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=🏴‍☠️ 追加规则`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]DIRECT
custom_proxy_group=⚓ GitHub`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]DIRECT
custom_proxy_group=🇨🇳 追加规则`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=💬 Ai`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=☁ 🅲🅵`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]DIRECT
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=🎥 奈飞视频`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]🎥 奈飞节点
custom_proxy_group=📺 巴哈姆特`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=Ⓜ️ 微软云盘`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 手动切换`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 手动切换
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🛑 🇨🇳 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🚀 手动切换`[]☁ Oracle节点`[]☁ Free 节点`[]☁ AWS节点`[]☁ Azure节点`[]☁ Google节点`[]DIRECT
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=☁ Oracle节点`url-test`(Oracle)`http://www.gstatic.com/generate_204`666,,1888
custom_proxy_group=☁ AWS节点`url-test`(AWS)`http://www.gstatic.com/generate_204`666,,1888
custom_proxy_group=☁ Google节点`url-test`(Google|GCP)`http://www.gstatic.com/generate_204`666,,1888
custom_proxy_group=☁ Azure节点`url-test`(Azure)`http://www.gstatic.com/generate_204`666,,1888
custom_proxy_group=☁ Free 节点`url-test`(Free)`http://www.gstatic.com/generate_204`666,,1888




;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/siren202101/clash/refs/heads/main/GeneralClashConfig.yml


;luck
